version: '3.8'
services:
  mint:
    build:
      context: ./Docker
      dockerfile: Dockerfile
      args:
        - project_name=${PROJECT_NAME}
    volumes:
      - ${WORKSPACE}:/${PROJECT_NAME}
    ports:
      - ${WEB_SERVER_PORT}:3000
